### PR TITLE
node support :)

### PR DESCRIPTION
**Pull request by M1noa**
make it have node support so you can publich via vercel or smthen if you want, lmk if u need help

### CODE REVIEW

**Comment by cybercrimecat** [comment]
ill do it for a bj and a snickers bar

**Comment by M1noa** [comment]
i already made it you just gotta commit it if you want it, i also made the
unlisted folder not accessible and made the list of posts auto update

**Comment by cybercrimecat** [comment]
ill commit it for a bj and a snickers bar

**Comment by M1noa** [comment]
idc if u commit it lol, i just made it cuz i was bored

**Pull request closed without merging**
